#ifndef GLOBAL_H
#define GLOBAL_H

enum ObjectSelections {
  triggermatch_e = long(1) << 1,
  triggermatch_e2 = long(1) << 2,
  triggermatch_e3 = long(1) << 3,
  triggermatch_mu = long(1) << 4,
  triggermatch_mu2 = long(1) << 5,
  triggermatch_mu3 = long(1) << 6,
  bm_e_passIP = long(1) << 7,
  bm_e2_passIP = long(1) << 8,
  bm_e3_passIP = long(1) << 9,
  bm_mu_passIP = long(1) << 10,
  bm_mu2_passIP = long(1) << 11,
  bm_mu3_passIP = long(1) << 12,
  bm_gam_idLoose = long(1) << 13,
  bm_gam_idTight = long(1) << 14,
  bm_gam_isoTight = long(1) << 15,
  bm_gam_isoLoose = long(1) << 16,
  bm_gam_isLoosePrime2 = long(1) << 17,
  bm_gam_isLoosePrime3 = long(1) << 18,
  bm_gam_isLoosePrime4a = long(1) << 19,
  bm_gam_isLoosePrime5 = long(1) << 20,
  bm_mu_idLoose = long(1) << 21,
  bm_mu_idMedium = long(1) << 22,
  bm_mu_idTight = long(1) << 23,
  bm_mu_isoPflowLoose_VarRad = long(1) << 24,
  bm_mu_isoPflowTight_VarRad = long(1) << 25,
  bm_mu2_idLoose = long(1) << 26,
  bm_mu2_idMedium = long(1) << 27,
  bm_mu2_idTight = long(1) << 28,
  bm_mu2_isoPflowLoose_VarRad = long(1) << 29,
  bm_mu2_isoPflowTight_VarRad = long(1) << 30,
  bm_mu3_idLoose = long(1) << 31,
  bm_mu3_idMedium = long(1) << 32,
  bm_mu3_idTight = long(1) << 33,
  bm_mu3_isoPflowLoose_VarRad = long(1) << 34,
  bm_mu3_isoPflowTight_VarRad = long(1) << 35,
  bm_e_idLoose = long(1) << 35,
  bm_e_idMedium = long(1) << 36,
  bm_e_idTight = long(1) << 37,
  bm_e_isoLooseVarRad = long(1) << 38,
  bm_e_isoTightVarRad = long(1) << 39,
  bm_e2_idLoose = long(1) << 40,
  bm_e2_idMedium = long(1) << 41,
  bm_e2_idTight = long(1) << 42,
  bm_e2_isoLooseVarRad = long(1) << 43,
  bm_e2_isoTightVarRad = long(1) << 44,
  bm_e3_idLoose = long(1) << 45,
  bm_e3_idMedium = long(1) << 46,
  bm_e3_idTight = long(1) << 47,
  bm_e3_isoLooseVarRad = long(1) << 47,
  bm_e3_isoTightVarRad = long(1) << 48,
};
enum EventSelections {
  all = long(1) << 0,
  fjvt = long(1) << 1,
  init = long(1) << 2,
  trigger = long(1) << 3,
  primary_vertex = long(1) << 4,
  dq = long(1) << 5,
  duplicate = long(1) << 6,
  jetclean = long(1) << 7,
  onelep = long(1) << 8,
  metcut = long(1) << 9,
  onegam = long(1) << 10,
  twojet = long(1) << 11,
  mjj = long(1) << 12,
  second_lepton_veto = long(1) << 13,
  ly_Z_veto = long(1) << 14,
  dphi = long(1) << 15,
  dr = long(1) << 16,
  onelep_truth = long(1) << 17,
  onegam_truth = long(1) << 18,
  trigger_pt_truth = long(1) << 19,
  ly_Z_veto_truth = long(1) << 20,
  twojet_truth = long(1) << 21,
  dphi_truth = long(1) << 22,
  dr_truth = long(1) << 23,
  vy_OR = long(1) << 24,
  Wenu = long(1) << 25,
  Wmunu = long(1) << 26,
  Wenu_truth = long(1) << 27,
  Wmunu_truth = long(1) << 28,
};

#endif
